### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/68#2]
I should probably publish this on Google Play.

# TODO
- [ ] Draw a logo (green and white with 68 inside)
- [ ] A button to open Battery Usage
- [ ] Introduce Greenify
- [ ] Ask users to use dark mode
- [ ] Link to GitHub
